#!/bin/sh
#

CDROM_MOUNT="$1"

for d in "$CDROM_MOUNT"/dists/*/main/dist-upgrader/binary-all/; do
    if [ -d "$d" ]; then
        UPGRADER_DIR="$d"
        break
    fi
done

TAR=$(basename "$UPGRADER_DIR"/*.tar.gz)
CODENAME=${TAR%.tar.gz}

# get a tempdir
TMPDIR=$(mktemp -t -d distupgrade.XXXXXX)
cd $TMPDIR

# extract the tar
tar xzf "$UPGRADER_DIR"/"$TAR"

# run it
gksu -- "$TMPDIR"/"$CODENAME" --cdrom "$CDROM_MOUNT"
