#!/bin/sh

set -e

case "$1" in
	remove)
		if which update-initramfs >/dev/null 2>&1
		then
			update-initramfs -u
		fi
		;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d cryptdisks remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d cryptdisks-early remove >/dev/null
fi
# End automatically added section

