#!/bin/sh
# $Id: preinst 224 2011-03-04 14:05:50Z robert $
# vim:ts=4:sts=4:et:sw
# preinst for doc-base

# Abort if any command returns an error value
set -e

package=doc-base
infodir="/var/lib/$package/info"
docsdir="/var/lib/$package/documents"
omfdir="/var/lib/$package/omf"
compatver=0.10.0~


remove_obsolete() {
    rm -rf /var/lib/doc-base
}


if [ "$1" = "upgrade" ] &&  dpkg --compare-versions "$2" lt-nl "$compatver"; then
    remove_obsolete
fi




exit 0

