#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -f /usr/share/apport/package-hooks/source_evince.pyc
fi

# Automatically added by dh_apparmor
if [ "$1" = "purge" ]; then
    rm -f "/etc/apparmor.d/disable/usr.bin.evince" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.evince" || true
    rm -f "/etc/apparmor.d/local/usr.bin.evince" || true
    rmdir /etc/apparmor.d/local 2>/dev/null || true
fi
# End automatically added section

