#!/bin/sh

set -e

case "$1" in
  purge)
    rm -rf /etc/gtk-2.0
  ;;
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section


if [ -d /usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules ]; then
    # Purge the cache
    rm -f /usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/gtk.immodules
    rmdir -p --ignore-fail-on-non-empty /usr/lib/i386-linux-gnu/gtk-2.0/2.10.0
fi
