#!/bin/sh
#
# This is the postinst script for the Debian GNU/Linux time package
#
# Written by Dirk Eddelbuettel <edd@debian.org>   

set -e 

 

case "$1" in
    configure)
	install-info --quiet --section "General commands" "General commands:" \
	    --description="A utility to time the execution of a command" time.info.gz
	#
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
	;;
    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
	;;
esac


