#! /bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -e /etc/rc2.d/S20ubiquity ]; then
	update-rc.d -f ubiquity remove >/dev/null 2>&1
fi

# Automatically added by dh_installinit
update-rc.d -f ubiquity remove >/dev/null || exit $?
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p ubiquity /usr/lib/ubiquity -V 2.7
fi

# End automatically added section


exit 0
