#!/bin/sh

# This script makes anacron jobs start/stop when a machine gets or loses AC
# power.

# The /etc/init.d/anacron script now normally tries to avoid running anacron
# unless on AC power, so as to avoid running down the battery.  (Things like
# the slocate updatedb cause a lot of I/O.)  Rather than trying to
# second-guess which events reflect having or not having power, we just try to
# run anacron every time and let it abort if there's no AC.  You'll see a
# message on the cron syslog facility (typically /var/log/cron) if it does
# run.

case $1 in
    false)
	start -q anacron || :
	;;
    true)
	stop -q anacron || :
	;;
esac
