# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ubuntuone/storageprotocol/dircontent.proto',
  package='ubuntuone.storageprotocol',
  serialized_pb='\n*ubuntuone/storageprotocol/dircontent.proto\x12\x19ubuntuone.storageprotocol\"d\n\x0e\x44irectoryEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\x0c\x12\x36\n\tnode_type\x18\x03 \x01(\x0e\x32#.ubuntuone.storageprotocol.NodeType\"N\n\x10\x44irectoryContent\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).ubuntuone.storageprotocol.DirectoryEntry*0\n\x08NodeType\x12\r\n\tDIRECTORY\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x12\x0b\n\x07SYMLINK\x10\x02\x42\x39\n\x1d\x63om.ubuntuone.storageprotocolB\x18\x44irectoryContentProtocol')

_NODETYPE = descriptor.EnumDescriptor(
  name='NodeType',
  full_name='ubuntuone.storageprotocol.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DIRECTORY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FILE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SYMLINK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=255,
  serialized_end=303,
)


DIRECTORY = 0
FILE = 1
SYMLINK = 2



_DIRECTORYENTRY = descriptor.Descriptor(
  name='DirectoryEntry',
  full_name='ubuntuone.storageprotocol.DirectoryEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='ubuntuone.storageprotocol.DirectoryEntry.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node', full_name='ubuntuone.storageprotocol.DirectoryEntry.node', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node_type', full_name='ubuntuone.storageprotocol.DirectoryEntry.node_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=73,
  serialized_end=173,
)


_DIRECTORYCONTENT = descriptor.Descriptor(
  name='DirectoryContent',
  full_name='ubuntuone.storageprotocol.DirectoryContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='ubuntuone.storageprotocol.DirectoryContent.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=175,
  serialized_end=253,
)

_DIRECTORYENTRY.fields_by_name['node_type'].enum_type = _NODETYPE
_DIRECTORYCONTENT.fields_by_name['entries'].message_type = _DIRECTORYENTRY
DESCRIPTOR.message_types_by_name['DirectoryEntry'] = _DIRECTORYENTRY
DESCRIPTOR.message_types_by_name['DirectoryContent'] = _DIRECTORYCONTENT

class DirectoryEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIRECTORYENTRY
  
  # @@protoc_insertion_point(class_scope:ubuntuone.storageprotocol.DirectoryEntry)

class DirectoryContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIRECTORYCONTENT
  
  # @@protoc_insertion_point(class_scope:ubuntuone.storageprotocol.DirectoryContent)

# @@protoc_insertion_point(module_scope)
