=head1 NAME

Pango::AttrFontDesc - Pango description of a font

=cut

=for object Pango::AttrFontDesc - Pango description of a font

=cut




=head1 METHODS

=head2 attribute = Pango::AttrFontDesc-E<gt>B<new> ($font_desc, ...)

=over

=item * $font_desc (Pango::FontDescription) 

=item * ... (list) 

=back

=head2 fontdescription = $attr-E<gt>B<desc> (...)

=over

=item * ... (list) 

=back



=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

