=head1 NAME

Pango::AttrVariant - Pango font variant attribute

=cut

=for object Pango::AttrVariant - Pango font variant attribute

=cut




=head1 METHODS

=head2 attribute = Pango::AttrVariant-E<gt>B<new> ($variant, ...)

=over

=item * $variant (Pango::Variant) 

=item * ... (list) 

=back

=head2 variant = $attr-E<gt>B<value> (...)

=over

=item * ... (list) 

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum Pango::Variant

=over

=item * 'normal' / 'PANGO_VARIANT_NORMAL'

=item * 'small-caps' / 'PANGO_VARIANT_SMALL_CAPS'

=back




=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

