=head1 NAME

Pango::AttrSize - Pango font-size attribute

=cut

=for object Pango::AttrSize - Pango font-size attribute

=cut




=head1 METHODS

=head2 attribute = Pango::AttrSize-E<gt>B<new> ($size, ...)

=over

=item * $size (integer) 

=item * ... (list) 

=back

=head2 attribute = Pango::AttrSize-E<gt>B<new_absolute> ($size, ...)

=over

=item * $size (integer) 

=item * ... (list) 

=back

Since: pango 1.8



=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

