=head1 NAME

Pango::AttrRise - Pango baseline displacement attribute

=cut

=for object Pango::AttrRise - Pango baseline displacement attribute

=cut




=head1 METHODS

=head2 attribute = Pango::AttrRise-E<gt>B<new> ($rise, ...)

=over

=item * $rise (integer) 

=item * ... (list) 

=back



=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

