=head1 NAME

Pango::AttrStrikethrough - Pango strike-through attribute

=cut

=for object Pango::AttrStrikethrough - Pango strike-through attribute

=cut




=head1 METHODS

=head2 attribute = Pango::AttrStrikethrough-E<gt>B<new> ($strikethrough, ...)

=over

=item * $strikethrough (boolean) 

=item * ... (list) 

=back

=head2 boolean = $attr-E<gt>B<value> (...)

=over

=item * ... (list) 

=back



=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

