=head1 NAME

Pango::AttrBackground - Pango background color attribute

=cut

=for object Pango::AttrBackground - Pango background color attribute

=cut




=head1 METHODS

=head2 attribute = Pango::AttrBackground-E<gt>B<new> ($red, $green, $blue, ...)

=over

=item * $red (unsigned) 

=item * $green (integer) 

=item * $blue (unsigned) 

=item * ... (list) 

=back



=cut


=head1 SEE ALSO

L<Pango>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2009 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Pango> for a full notice.



=cut

