
=head1 NAME

Pango - API Reference Pod Index

=head1 PAGES

=over

=item L<Pango>

=item L<Pango::AttrBackground>

=item L<Pango::AttrColor>

=item L<Pango::AttrFallback>

=item L<Pango::AttrFamily>

=item L<Pango::AttrFontDesc>

=item L<Pango::AttrForeground>

=item L<Pango::AttrGravity>

=item L<Pango::AttrGravityHint>

=item L<Pango::AttrInt>

=item L<Pango::AttrIterator>

=item L<Pango::AttrLanguage>

=item L<Pango::AttrLetterSpacing>

=item L<Pango::AttrList>

=item L<Pango::AttrRise>

=item L<Pango::AttrScale>

=item L<Pango::AttrShape>

=item L<Pango::AttrSize>

=item L<Pango::AttrStretch>

=item L<Pango::AttrStrikethrough>

=item L<Pango::AttrStrikethroughColor>

=item L<Pango::AttrString>

=item L<Pango::AttrStyle>

=item L<Pango::AttrUnderline>

=item L<Pango::AttrUnderlineColor>

=item L<Pango::AttrVariant>

=item L<Pango::AttrWeight>

=item L<Pango::Attribute>

=item L<Pango::Cairo>

=item L<Pango::Cairo::Context>

=item L<Pango::Cairo::Font>

=item L<Pango::Cairo::FontMap>

=item L<Pango::Color>

=item L<Pango::Context>

=item L<Pango::Font>

=item L<Pango::FontDescription>

=item L<Pango::FontFace>

=item L<Pango::FontFamily>

=item L<Pango::FontMap>

=item L<Pango::FontMetrics>

=item L<Pango::Fontset>

=item L<Pango::Gravity>

=item L<Pango::Language>

=item L<Pango::Layout>

=item L<Pango::LayoutIter>

=item L<Pango::LayoutLine>

=item L<Pango::Matrix>

=item L<Pango::Renderer>

=item L<Pango::Script>

=item L<Pango::ScriptIter>

=item L<Pango::TabArray>

=item L<Pango::version>

=back

